"use client";
import { useMemo, useRef, useState } from "react";
import { ImageIcon, Send, Square, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { MessageBubble, type ChatMessage } from "@/components/chat/message-bubble";
import { ModelSelector, type ModelOption } from "@/components/chat/model-selector";
import { Logo } from "@/components/brand/logo";

export function ChatClient({conversationId:initialId,initialMessages,models,initialModelId}:{conversationId?:string;initialMessages:ChatMessage[];models:ModelOption[];initialModelId:string}){
 const [messages,setMessages]=useState(initialMessages); const [conversationId,setConversationId]=useState(initialId); const [mode,setMode]=useState<"text"|"image">("text"); const [modelId,setModelId]=useState(initialModelId); const [text,setText]=useState(""); const [busy,setBusy]=useState(false); const abortRef=useRef<AbortController|null>(null);
 const imageModels=useMemo(()=>models.filter(m=>m.kind==="image"),[models]); const textModels=useMemo(()=>models.filter(m=>m.kind!=="image"),[models]);
 const selectedValid=mode==="image"?imageModels.some(m=>m.id===modelId):textModels.some(m=>m.id===modelId);
 const effectiveModelId=selectedValid?modelId:(mode==="image"?imageModels[0]?.id:textModels[0]?.id)??"";
 async function send(){const prompt=text.trim();if(!prompt||busy||!effectiveModelId)return;setText("");setBusy(true);const userMessage:ChatMessage={id:crypto.randomUUID(),role:"user",content:prompt};setMessages(m=>[...m,userMessage]);
  if(mode==="image"){
   try{const r=await fetch("/api/images",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({conversationId,modelId:effectiveModelId,prompt})});const j=await r.json();if(!r.ok)throw new Error(j.error??"Generation failed");setConversationId(j.conversationId);window.history.replaceState(null,"",`/chat/${j.conversationId}`);setMessages(m=>[...m,j.message]);}catch(e){toast.error(e instanceof Error?e.message:"Erreur image");}finally{setBusy(false);}return;
  }
  const assistantId=crypto.randomUUID();setMessages(m=>[...m,{id:assistantId,role:"assistant",content:"",pending:true}]);const controller=new AbortController();abortRef.current=controller;
  try{const r=await fetch("/api/chat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({conversationId,modelId:effectiveModelId,message:prompt}),signal:controller.signal});if(!r.ok){const j=await r.json().catch(()=>({}));throw new Error(j.error??`Erreur ${r.status}`);}const id=r.headers.get("x-conversation-id");if(id){setConversationId(id);window.history.replaceState(null,"",`/chat/${id}`);}const reader=r.body?.getReader();if(!reader)throw new Error("Flux indisponible");const decoder=new TextDecoder();let buffer="";while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split("\n");buffer=lines.pop()??"";for(const line of lines){if(!line.trim())continue;const event=JSON.parse(line);if(event.type==="delta")setMessages(m=>m.map(x=>x.id===assistantId?{...x,content:x.content+event.text}:x));if(event.type==="usage")setMessages(m=>m.map(x=>x.id===assistantId?{...x,total_tokens:event.totalTokens,cost_usd:event.costUsd,model_snapshot:event.model}:x));if(event.type==="error")throw new Error(event.message);}}
  }catch(e){if((e as Error).name!=="AbortError")toast.error(e instanceof Error?e.message:"Erreur de génération");}finally{setMessages(m=>m.map(x=>x.id===assistantId?{...x,pending:false}:x));setBusy(false);abortRef.current=null;}
 }
 return <div className="flex h-[calc(100vh-4rem)] flex-col lg:h-screen"><div className="flex h-16 shrink-0 items-center justify-between border-b border-zinc-200/70 px-4 dark:border-white/10 sm:px-6"><div className="lg:hidden"><Logo compact/></div><ModelSelector models={models} value={effectiveModelId} onChange={setModelId} kind={mode}/><div className="text-xs text-zinc-500">{typeof window!=="undefined"&&window.sophenicDesktop?.isDesktop?"Windows":"Web"}</div></div><div className="min-h-0 flex-1 overflow-y-auto"><div className="mx-auto max-w-3xl px-4">{messages.length===0?<div className="grid min-h-[58vh] place-items-center text-center"><div><div className="mx-auto mb-5 grid size-14 place-items-center rounded-2xl bg-gradient-to-br from-indigo-500 to-violet-500 text-white shadow-xl shadow-indigo-500/20"><Sparkles/></div><h1 className="text-3xl font-semibold tracking-tight">Que voulez-vous créer ?</h1><p className="mt-2 text-sm text-zinc-500">Choisissez votre modèle, puis commencez une conversation.</p></div></div>:messages.map(m=><MessageBubble key={m.id} message={m}/>)}</div></div><div className="shrink-0 border-t border-zinc-200/70 bg-white/80 p-3 backdrop-blur-xl dark:border-white/10 dark:bg-zinc-950/80"><div className="mx-auto max-w-3xl"><div className="mb-2 flex gap-2"><Button size="sm" variant={mode==="text"?"default":"ghost"} onClick={()=>setMode("text")}><Sparkles className="size-3.5"/>Texte / code</Button><Button size="sm" variant={mode==="image"?"default":"ghost"} disabled={imageModels.length===0} onClick={()=>setMode("image")}><ImageIcon className="size-3.5"/>Image</Button></div><div className="relative"><Textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send();}}} placeholder={mode==="image"?"Décrivez l’image à générer…":"Écrivez à Sophenic…"} className="min-h-20 pr-14"/><div className="absolute bottom-2.5 right-2.5">{busy?<Button size="icon" variant="outline" onClick={()=>abortRef.current?.abort()}><Square className="size-4"/></Button>:<Button size="icon" variant="accent" onClick={()=>void send()} disabled={!text.trim()}><Send className="size-4"/></Button>}</div></div><p className="mt-2 text-center text-[11px] text-zinc-500">Sophenic peut faire des erreurs. Vérifiez les informations importantes.</p></div></div></div>
}
