"use client";
import { useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
type U={id:string;email:string;role:string;plan_id:string};
export function AdminUsers({initial}:{initial:U[]}){const [rows,setRows]=useState(initial);const save=async(u:U)=>{const r=await fetch(`/api/admin/users/${u.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({role:u.role,planId:u.plan_id})});r.ok?toast.success("Utilisateur mis à jour"):toast.error("Mise à jour impossible")};return <div className="overflow-x-auto rounded-2xl border border-zinc-200 dark:border-white/10"><table className="w-full text-left text-sm"><thead className="bg-zinc-100/70 text-xs text-zinc-500 dark:bg-white/5"><tr><th className="p-3">Utilisateur</th><th>Rôle</th><th>Plan</th><th></th></tr></thead><tbody>{rows.map((u,i)=><tr key={u.id} className="border-t border-zinc-200 dark:border-white/10"><td className="p-3">{u.email}</td><td><select className="rounded-lg bg-transparent" value={u.role} onChange={e=>setRows(r=>r.map((x,j)=>j===i?{...x,role:e.target.value}:x))}><option>user</option><option>support</option><option>admin</option></select></td><td><select className="rounded-lg bg-transparent" value={u.plan_id} onChange={e=>setRows(r=>r.map((x,j)=>j===i?{...x,plan_id:e.target.value}:x))}><option>free</option><option>pro</option><option>business</option></select></td><td className="p-2"><Button size="sm" variant="outline" onClick={()=>save(u)}>Enregistrer</Button></td></tr>)}</tbody></table></div>}
type P={id:string;name:string;daily_token_limit:number;monthly_token_limit:number;monthly_cost_limit_usd:number|string};
export function AdminPlans({initial}:{initial:P[]}){const [rows,setRows]=useState(initial);const field=(i:number,k:keyof P,v:string)=>setRows(r=>r.map((x,j)=>j===i?{...x,[k]:Number(v)}:x));const save=async(p:P)=>{const r=await fetch(`/api/admin/plans/${p.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({dailyTokenLimit:Number(p.daily_token_limit),monthlyTokenLimit:Number(p.monthly_token_limit),monthlyCostLimitUsd:Number(p.monthly_cost_limit_usd)})});r.ok?toast.success(`Limites ${p.name} enregistrées`):toast.error("Erreur")};return <div className="grid gap-3 lg:grid-cols-3">{rows.map((p,i)=><div key={p.id} className="rounded-2xl border border-zinc-200 p-4 dark:border-white/10"><div className="mb-4 font-medium">{p.name}</div><label className="text-xs text-zinc-500">Tokens / 24 h</label><Input type="number" value={p.daily_token_limit} onChange={e=>field(i,"daily_token_limit",e.target.value)}/><label className="mt-3 block text-xs text-zinc-500">Tokens / mois</label><Input type="number" value={p.monthly_token_limit} onChange={e=>field(i,"monthly_token_limit",e.target.value)}/><label className="mt-3 block text-xs text-zinc-500">Budget USD / mois</label><Input type="number" step="0.01" value={p.monthly_cost_limit_usd} onChange={e=>field(i,"monthly_cost_limit_usd",e.target.value)}/><Button className="mt-4 w-full" size="sm" onClick={()=>save(p)}>Sauvegarder</Button></div>)}</div>}

type M={id:string;name:string;provider:string;openrouter_id:string;enabled:boolean;kind:string};
export function AdminModels({initial}:{initial:M[]}){const [rows,setRows]=useState(initial);const toggle=async(m:M)=>{const enabled=!m.enabled;const r=await fetch(`/api/admin/models/${m.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({enabled})});if(r.ok)setRows(x=>x.map(v=>v.id===m.id?{...v,enabled}:v));else toast.error("Modification impossible")};return <div className="grid gap-2 sm:grid-cols-2">{rows.map(m=><div key={m.id} className="flex items-center gap-3 rounded-xl border border-zinc-200 p-3 dark:border-white/10"><div className="min-w-0 flex-1"><div className="truncate text-sm font-medium">{m.name}</div><div className="truncate text-xs text-zinc-500">{m.openrouter_id} · {m.kind}</div></div><Button size="sm" variant={m.enabled?"default":"outline"} onClick={()=>toggle(m)}>{m.enabled?"Actif":"Inactif"}</Button></div>)}</div>}
